Repository mfem/PyMFEM, pull requests merged in 2024-08, with the labels that each got.

#234 Ex39 dev
  data/compass.geo
  data/compass.mesh
  data/compass.msh
  examples/ex39.py
  examples/ex39p.py
  mfem/_par/attribute_sets.i
  mfem/_ser/attribute_sets.i
  mfem/par.py
  mfem/ser.py
Labels: enhancement

#235 Fix ex18 v2
  examples/ex18.py
  examples/ex18_common.py
  examples/ex18p.py
  mfem/_par/hyperbolic.i
  mfem/_par/setup.py
  mfem/_ser/hyperbolic.i
  mfem/_ser/setup.py
  mfem/common/bilininteg_ext.i
  mfem/par.py
  mfem/ser.py
Labels: In-progress

#238 added minor fix to ex23 and ex39p.
  examples/ex23.py
  examples/ex39p.py
Labels: minor

#243 add condition to skip if label='skip-ci'
  .github/workflows/build-and-test-dispatch.yml
  .vscode/settings.json
  ci_scripts/add_cuda_10_1.sh
  ci_scripts/add_cuda_11_1.sh
  ci_scripts/add_cuda_11_5.sh
Labels: skip-ci

#246 Install.md
  INSTALL.md
  README.md
  docs/install.txt
Labels: minor, skip-ci

#244 Documentation for PyMFEM 4.7 release
  docs/changelog.txt
Labels: skip-ci

#231 PyMFEM4.7
  .github/workflows/build-and-test-callable.yml
  .github/workflows/build-and-test-dispatch.yml
  .github/workflows/release_binary.yml
  .github/workflows/testrelease_binary.yml
  data/compass.geo
  data/compass.mesh
  data/compass.msh
  docs/changelog.txt
  examples/ex18.py
  examples/ex18_common.py
  examples/ex18p.py
  examples/ex23.py
  examples/ex25.py
  examples/ex39.py
  examples/ex39p.py
  mfem/__init__.py
  mfem/_par/attribute_sets.i
  mfem/_par/hyperbolic.i
  mfem/_par/setup.py
  mfem/_ser/attribute_sets.i
  mfem/_ser/hyperbolic.i
  mfem/_ser/setup.py
  mfem/common/bilininteg_ext.i
  mfem/common/generate_lininteg_ext.py
  mfem/par.py
  mfem/ser.py
  setup.py
Labels: enhancement

#249 Fix some wrapper code not handling mfem::real_t correctly
  mfem/__init__.py
  mfem/_par/hypre.i
  mfem/_par/sparsemat.i
  mfem/_ser/sparsemat.i
Labels: bug
